import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SellerShell } from "@/components/seller/seller-shell";
import { Card } from "@/components/ui/card";
import { ButtonLink } from "@/components/ui/button";
import { Chip } from "@/components/ui/chip";
import { formatAreaPath, formatDate, formatExactInr } from "@/lib/format";
import { getServices } from "@/lib/services";
import { runtimeConfig } from "@/lib/config/runtime";
import {
  NOT_SCORED_LABEL,
  NO_QUALIFICATION_DETAIL,
} from "@/lib/domain/commerce-display";

/**
 * Read per-account at request time: with a backend store selected this page
 * calls kkl-backend as the signed-in account, which cannot be prerendered.
 */
export const dynamic = "force-dynamic";

export const metadata: Metadata = { title: "Purchased lead" };

/** S-13 — purchased lead detail, with contact details and export. */
export default async function PurchasedLeadPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const lead = await getServices().leadMarket.getPurchased(id);
  if (!lead) notFound();

  const q = lead.qualification;

  return (
    <SellerShell title={`Lead ${lead.id}`} subtitle="Purchased · full contact details">
      <div className="grid grid-cols-[minmax(0,1fr)_340px] gap-[18px] max-[1200px]:grid-cols-1">
        <div className="flex flex-col gap-[16px]">
          <Card className="p-[22px]">
            <div className="flex flex-wrap items-center gap-[10px]">
              <p className="t-mono text-[13px] text-muted">{lead.id}</p>
              <Chip tone="success">Purchased</Chip>
            </div>
            <h2 className="t-flow-title mt-[3px] text-ink">{lead.requirement}</h2>
            <p className="t-body mt-[2px] text-muted">
              {formatAreaPath(lead.locationPath)}
            </p>

            <dl className="mt-[16px] grid grid-cols-2 gap-[14px] rounded-[10px] border border-line bg-tint p-[16px] max-[560px]:grid-cols-1">
              <Detail label="Name" value={lead.contact.name} />
              <Detail label="Mobile" value={lead.contact.phone} mono />
              <Detail label="Email" value={lead.contact.email ?? "Not provided"} />
              <Detail
                label="Best time to call"
                value={lead.contact.bestTimeToCall ?? "Not given"}
              />
            </dl>
          </Card>

          <Card className="p-[22px]">
            <h3 className="t-card-title text-ink">Qualification</h3>
            <dl className="mt-[12px] grid grid-cols-3 gap-px overflow-hidden rounded-[10px] border border-line bg-line max-[720px]:grid-cols-2">
              <Fact label="Budget band" value={lead.budgetBand} />
              <Fact label="Location" value={formatAreaPath(lead.locationPath)} />
              <Fact label="Configuration" value={lead.configuration} />
              <Fact label="Timeline" value={q?.timeline ?? NOT_SCORED_LABEL} />
              <Fact label="Purpose" value={q?.purpose ?? NOT_SCORED_LABEL} />
              <Fact label="Financing" value={q?.financing ?? NOT_SCORED_LABEL} />
            </dl>
            <p className="t-body mt-[14px] text-body">{q ? q.summary : NO_QUALIFICATION_DETAIL}</p>
            <div className="mt-[12px] flex flex-wrap gap-[8px]">
              <Chip tone="neutral">
                {q ? `Intent score ${q.intentScore}/100` : NOT_SCORED_LABEL}
              </Chip>
              {/* An absent call is an absent consent record, never a neutral
                  one: this lead was bought, and whether its enquirer agreed to
                  be contacted is exactly the thing not to soften. */}
              {q?.consentCaptured ? (
                <Chip tone="success">Consent captured</Chip>
              ) : (
                <Chip tone="warning">No consent captured</Chip>
              )}
              <Chip tone="muted">{q?.channel ?? "No call recorded"}</Chip>
            </div>
          </Card>
        </div>

        <aside className="flex flex-col gap-[16px]">
          <Card className="p-[22px]">
            <h3 className="t-card-title text-ink">Download</h3>
            <p className="t-body mt-[6px] text-body">
              Export this lead with its qualification answers.
            </p>
            <ButtonLink
              href={`/seller/purchased/${lead.id}/export.csv`}
              prefetch={false}
              className="mt-[14px] w-full"
            >
              Download CSV
            </ButtonLink>
            <p className="t-caption mt-[10px] text-muted">
              The file is generated by the server from this lead, so the browser never holds a
              list it was not given. In production the export is logged against your account;{" "}
              {runtimeConfig.isSampleMode
                ? "nothing is logged in sample mode."
                : "that logging is kkl-backend's."}{" "}
              Re-downloading does not cost credits.
            </p>
          </Card>

          <Card className="p-[22px]">
            <h3 className="t-card-title text-ink">Order</h3>
            <dl className="mt-[10px] flex flex-col gap-[10px]">
              <Detail label="Order reference" value={lead.orderId} mono />
              <Detail label="Purchased" value={formatDate(lead.purchasedAt)} />
              <Detail label="Credits paid" value={formatExactInr(lead.pricePaidCredits)} />
            </dl>
            {/* CR04: the order is its own record — what was paid, how, and what
                paperwork exists. This screen is the lead; that one is the order. */}
            <ButtonLink
              href={`/seller/orders/${lead.orderId}`}
              variant="secondary"
              className="mt-[14px] w-full"
            >
              Order and payment
            </ButtonLink>
            <ButtonLink href="/seller/purchased" variant="secondary" className="mt-[8px] w-full">
              All my leads
            </ButtonLink>
          </Card>
        </aside>
      </div>
    </SellerShell>
  );
}

function Detail({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) {
  return (
    <div>
      <dt className="t-caption text-muted">{label}</dt>
      <dd className={`mt-[1px] text-[15px] font-bold text-ink ${mono ? "t-mono" : ""}`}>{value}</dd>
    </div>
  );
}

function Fact({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-white px-[15px] py-[12px]">
      <dt className="t-caption text-muted">{label}</dt>
      <dd className="mt-[1px] text-[15px] font-bold text-ink">{value}</dd>
    </div>
  );
}
